SEARCH_DIR("/lib/aarch64-linux-gnu/")
SEARCH_DIR("/usr/lib/aarch64-linux-gnu/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/aarch64-linux-gnu/12/")
SEARCH_DIR("./")
SEARCH_DIR("/home/pi/fronius/ApacheWebModule/")
SEARCH_DIR("/home/pi/fronius/Src/")
SEARCH_DIR("/home/pi/fronius/ApacheWebModule/extLibs/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_lz/lz_FpWeb/lib/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_lz/lz_SQLdb/lib/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_pl/pl_DBSQLUtils/lib/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseEngines/lib/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseEdit/lib/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseCodeTools/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/typhon/packager/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pastojs/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-db/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libgc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/a52/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fppkg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/mariadb/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/dblib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/proj4/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/mysql/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-stl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-pdf/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/tcl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-net/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-extra/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/zlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/graph/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/uuid/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/cairo/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/lua/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/regexpr/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libffi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pxlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libxml2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libusb/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-js/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fpindexer/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/testinsight/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-process/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libnettle/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gnutls/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libenet/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ibase/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libmagic/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-passrc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libpcre/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-sdo/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fastcgi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libvlc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/imagemagick/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/sdl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/utmp/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/imlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-mustache/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gdbint/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/bfd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/bzip2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/vcl-compat/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/tplylib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/openssl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fpmkunit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-extra/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/iconvenc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk1/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gst/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/jni/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fv/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/oracle/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/users/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gnome1/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/syslog/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/opengles/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/httpd22/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libmicrohttpd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/sqlite/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/cdrom/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pthreads/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gitlab/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/xforms/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-hash/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-sound/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ldap/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/dbus/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fpgtk/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libpng/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fftw/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ptc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-console/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/webidl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/openal/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libcurl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pas2js/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/odbc/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ggi/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/numlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/mad/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rsvg/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-css/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/firebird/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gmp/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/oggvorbis/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/modplug/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/odata/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libcups/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/postgres/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libtar/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/chm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/hermes/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/ncurses/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/httpd24/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/symbolic/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/unzip/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libfontconfig/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/newt/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-async/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gdbm/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/opengl/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/svgalib/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libsee/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/dts/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/zorba/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-res/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-unicode/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/aspell/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/hash/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/libgd/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-registry/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pcap/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/")
SEARCH_DIR("/usr/local/codetyphon/fpc/fpc64/bin/aarch64-linux/")
VERSION
{
  {
    global:
      fronius_module;
    local:
      *;
  };
}
INPUT(
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/dllprt0.o
/lib/aarch64-linux-gnu/crti.o
/usr/lib/gcc/aarch64-linux-gnu/12/crtbeginS.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/mod_fronius.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/mod_fronius.or
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/system.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/lnfodwrf.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/exeinfo.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/strings.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/fpintres.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/objpas.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/cthreads.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/sysutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/custapp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/httpd24/httpd24.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/interfaces.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/custapache24.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/fpapache24.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/froniusDataMod.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/pl_firebirddb.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.ModuleInit.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/linux.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/baseunix.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unix.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unixtype.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/initc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/dl.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/ctypes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/errors.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/sysconst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unixutil.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/classes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/singleinstance.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/types.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/typinfo.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/rtlconsts.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/sortbase.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/math.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/httpd24/apr24.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/cwstring.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/dynlibs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/unixcp.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2disableliboverlay.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2int.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/forms.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/xlib.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/x.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/gdk2x.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/gdk2pixbuf.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/gtk2.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/gdk2.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/glib2.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/pango.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lmessages.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclproc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclintf.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lcltype.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/dialogs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/controls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclstrconsts.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/graphics.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/menus.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/themes.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/buttons.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/stdctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/checklst.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/comctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/extctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclplatformdef.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/interfacebase.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wslclclasses.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wscontrols.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2winapiwindow.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2globals.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2proc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2def.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2fontcache.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2extra.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2msgqueue.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/graphtype.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/graphmath.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazfileutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutf8.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/dynhasharray.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/maps.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/integerlist.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazloggerbase.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laztracer.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutilities.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazstringutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/x11/xrender.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/cairo/cairo.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/atk.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsreferences.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/system.uitypes.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/fpcadds.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazclasses.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazmethodlist.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/strutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/translations.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/jsonscanner.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/jsonparser.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/fpjson.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/fileutil.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lconvencoding.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/avglvltree.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/stringhashlist.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-json/jsonreader.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/variants.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/contnrs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/varutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/masks.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutilsstrconsts.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/dos.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/codepagescommon.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/codepagesasian.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/avl_tree.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazdbglog.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazutf16.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/utf8process.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazsysutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpimage.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/intfgraphics.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazversion.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadbmp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritebmp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/bmpcomn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadpng.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritepng.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadtiff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritetiff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fptiffcmn.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclversion.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/icnstypes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpimgcmn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/pngcomn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zstream.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zbase.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/gzio.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/hash/crc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zdeflate.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/zinflate.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/trees.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/adler.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/infblock.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/infutil.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/infcodes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/inftrees.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/paszlib/inffast.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpcolorspace.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpcanvas.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadpnm.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritepnm.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadjpeg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritejpeg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadtga.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpwritetga.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpreadgif.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lresources.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclrescache.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/clipping.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/jpegcomn.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jpeglib.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdapimin.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdatasrc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdapistd.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jmorecfg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdeferr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jinclude.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jerror.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jmemmgr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmarker.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdinput.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcomapi.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jmemnobs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmaster.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdcolor.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdsample.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdpostct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jddctmgr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdphuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdhuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdcoefct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmainct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jquant1.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jquant2.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdmerge.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctfst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctint.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctflt.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jidctred.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcapistd.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcapimin.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jdatadst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcparam.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcinit.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcmarker.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcphuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jchuff.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcmaster.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jccolor.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcsample.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcprepct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcdctmgr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jccoefct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jcmainct.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jfdctint.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jfdctfst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pasjpeg/jfdctflt.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/targacmn.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazconfigstorage.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/dynqueue.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/syncobjs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/system.timespan.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/pthreads/pthreads.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/tmschema.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/fgl.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-process/process.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-process/pipes.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl/termio.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/buttonpanel.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclclasses.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/clipbrd.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/dialogres.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/customtimer.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/actnlist.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/helpintfs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/imglist.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fpimgcanv.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/fppixlcanv.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/pixtools.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/ellipses.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-image/polygonfilltools.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsimglist.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsproc.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsfactory.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/propertystorage.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/rttiutils.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsmenus.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/chm/fasthtmlparser.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsforms.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/imagelistcache.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/textstrings.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/extendedstrings.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsstdctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsbuttons.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/popupnotifier.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsextctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/toolwin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wscomctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wstoolwin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsdialogs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/taskdlgemulation.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/dateutils.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wschecklst.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/gtk2/gtk2ext.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/uriparser.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/extdlgs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclmessageglue.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2debug.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/calendar.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/calcform.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wscalendar.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsextdlgs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lclmemmanager.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsprivate.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazlinkedlist.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsfactory.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsstdctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wscontrols.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wschecklst.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2themes.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/spin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/grids.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/pairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsbuttons.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wscalendar.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wscomctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsdialogs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsextctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsextdlgs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsforms.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsgrids.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsimglist.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsmenus.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wsspin.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2wspairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/unitywsctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsspin.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/htmldefs.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/maskedit.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/dynamicarray.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlcfg.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lcsvutils.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/lazfilecache.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_dom.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlread.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlwrite.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/laz2_xmlutils.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsgrids.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wspairsplitter.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2cellrenderer.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/gtk2/gtk2listviewtreemodel.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/custweb.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/httpdefs.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/fphttp.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/httpprotocol.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/eventlog.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/httproute.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDatabase.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBSQL.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-web/fpweb.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.DBIntf.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.WebAuthnModuleInit.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.WebDataHandler.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/fptimer.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBExternals.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-db/db.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IB.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBInternals.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-objpas/fmtbcd.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/maskutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-db/dbconst.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBMessages.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBUtils.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBClientAPI.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25ClientAPI.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30ClientAPI.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBHeader.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBActivityMonitor.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-registry/registry.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/regexpr/regexpr.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/inifiles.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-registry/xmlreg.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/dom.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/xmlread.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/xmlwrite.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/xmlutils.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/dtdmodel.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/xmlreader.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-xml/xmltextreader.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Attachment.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Transaction.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Services.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBAttachment.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBTransaction.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBServices.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBParamBlock.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBOutputBlock.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBErrorCodes.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Events.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Blob.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Statement.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB25Array.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBEvents.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBBlob.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBSQLData.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBStatement.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBNumeric.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBArray.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/Firebird.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FBClientLib.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Attachment.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Services.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Transaction.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Statement.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Array.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Blob.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30Events.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/FB30TimeZoneServices.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBSQLMonitor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBCustomDataSet.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDatabaseInfo.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBMessages.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBBufferedCursors.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBBlob.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBSQLParser.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBQuery.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBIPC.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-extra/ipc.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-base/fptemplate.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.ActionsBase.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.Webauthn.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.Globals.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.Consts.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdTCPClient.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/WebauthnHandler.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdGlobal.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdExceptionCore.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdIOHandler.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdTCPConnection.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-extra/sockets.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/iconvenc/iconvenc.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdException.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdResourceStrings.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdStack.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdStackConsts.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdCTypes.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdStackUnix.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdStackBSDBase.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-net/netdb.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdResourceStringsUnix.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdAntiFreezeBase.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdBuffer.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdBaseComponent.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdComponent.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdIntercept.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdResourceStringsCore.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdIOHandlerSocket.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdIOHandlerStack.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdReply.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdSocketHandle.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdCustomTransparentProxy.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdSocks.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdAssignedNumbers.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdIPAddress.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdReplyRFC.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fido2.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/superobject.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/cbor.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/authData.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/cryptRandom.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fido2dll.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/generics.collections.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/generics.memoryexpanders.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/generics.defaults.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/generics.helpers.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/generics.strings.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/rtl-generics/generics.hashes.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdCoderMIME.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdCoder3to4.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdCoder.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdGlobalProtocols.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdCharsets.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_Indy/lib/aarch64-linux/gtk2/IdResourceStringsProtocols.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/OpenSSL1_1ForWebauthn.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.FidoDBData.o
/home/pi/fronius/ApacheWebModule/FPC/lib/aarch64-linux/Fronius.Sessions.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/allfirebirddbreg.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/dbFieldLinkPropEditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/dbFieldListPropEditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDatabaseEdit.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibdataseteditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibdeletesqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDSDialogs.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBEventsEditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibgeneratoreditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibinsertsqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibmodifysqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibrefreshsqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibselectsqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibserviceeditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBSQLEditFrame.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibsqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBTransactionEdit.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibupdatesqleditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXServiceEditor.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/DBControlGrid.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBArrayGrid.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDynamicGrid.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBLookupComboEditBox.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBTreeView.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBCMLocalDBSupport.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXCreateDatabaseDlg.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXCreateDatabaseFromSQLDlgUnit.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXSaveDatabaseDlg.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXUpgradeDatabaseDlg.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXViewLogDig.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBBatchMove.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDataOutput.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBDialogs.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBEvents.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBExtract.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBServices.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBStoredProc.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBTable.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBTypes.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBUpdate.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBUpdateSQL.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBVersion.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/ibxscript.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXServices.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/vsb_firebird.o
/usr/local/codetyphon/typhon/packager/units/aarch64-linux/typhonpackageintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/componenteditors.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/propedits.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/dbpropedits.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/fieldseditor.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/lazstringgridedit.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/checklistboxeditordlg.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/checkgroupeditordlg.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/propeditutils.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/componentreg.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/objinspstrconsts.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/idewindowintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/ideoptionsintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/lazideintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/baseideintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/compoptsintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/projectintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/ideexterntoolintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/packageintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/multiprojectintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/ideopteditorintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/srceditorintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/macrointf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/macrodefintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/newitemintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/projpackintf.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/buildstrconsts.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/packagedependencyintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/editorsyntaxhighlighterdef.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/idecommands.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/ideimagesintf.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/editbtn.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/valedit.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/filectrl.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/checkboxthemed.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/texttools.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/frmselectprops.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/stringspropeditdlg.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/keyvalpropeditdlg.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/collectionpropeditform.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/filefilterpropeditor.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/pagespropeditdlg.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/groupededit.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/calendarpopup.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/timepopup.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/shellctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/wsshellctrls.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/formeditingintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/objectinspector.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/idedialogs.o
/usr/local/codetyphon/typhon/components/BaseBuildIntf/units/aarch64-linux/lazmsgworker.o
/usr/local/codetyphon/typhon/components/BaseUtils/lib/aarch64-linux/compwriterpas.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/unitresources.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/treefilteredit.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/listfilteredit.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/idehelpintf.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/componenttreeview.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/oifavoriteproperties.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/changeparentdlg.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lazhelpintf.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/dbctrls.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/dbgrids.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/dbgridcolumnspropeditform.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/newfield.o
/usr/local/codetyphon/typhon/components/BaseIDEIntf/units/aarch64-linux/gtk2/fieldslist.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_DBSQLUtils/lib/aarch64-linux/gtk2/vsb_engine.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synhighlightersql.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedit.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittypes.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedithighlighter.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditstrconst.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synhighlighterhashentries.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditkeycmds.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittextbase.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmiscprocs.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/lazsynimmbase.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/messages.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/stdactns.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditsearch.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmousecmds.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditpointclasses.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synbeautifier.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarks.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkup.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkuphighall.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkupbracket.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkupwordgroup.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkupctrlmouselink.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkupspecialline.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkupselection.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmarkupspecialchar.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/lazsynedittext.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittextbuffer.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditlines.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittexttrimmer.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittexttabexpander.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittextdoublewidthchars.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditfoldedview.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syngutterbase.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syngutter.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syneditmiscclasses.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/lazsyntextarea.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syntextdrawer.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedittextbidichars.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synguttercodefolding.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syngutterchanges.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syngutterlinenumber.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synguttermarks.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/syngutterlineoverview.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/lazsyneditmousecmdstypes.o
/usr/local/codetyphon/typhon/components/BaseSynedit/units/aarch64-linux/gtk2/synedithighlighterfoldbase.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/graphutil.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lazcanvas.o
/usr/local/codetyphon/typhon/lcl/units/aarch64-linux/lazregions.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_DBSQLUtils/lib/aarch64-linux/gtk2/vsb_dlglink.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBLocalDBSupport.o
/usr/local/codetyphon/fpc/fpc64/units/aarch64-linux/fcl-db/memds.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/DBTreeView.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXCustomIBLocalDBSupport.o
/usr/local/codetyphon/typhon/components/packages_pl/pl_FirebirdDB/lib/aarch64-linux/gtk2/IBXUpgradeConfFile.o
)
INPUT(
-lpthread
-ldl
-lgdk-x11-2.0
-lgtk-x11-2.0
-lX11
-lgdk_pixbuf-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
-lrt
-lfido2
-lcrypto
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/aarch64-linux-gnu/12/crtendS.o
/lib/aarch64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
