/******************************************************************************/
/*            Generated by IBExpert 2023.1.3.1 28.03.2023 16:30:48            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

/* SET CLIENTLIB 'fbclient.dll'; 

CREATE DATABASE 'localhost:C:\Users\rabatscher\Documents\Embarcadero\Studio\Projekte\Fronius\DB\fronius.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;
*/
/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_FRONIUSUSERS_ID;
SET GENERATOR GEN_FRONIUSUSERS_ID TO 4;

CREATE GENERATOR GEN_USERCREDENTIALS_ID;
SET GENERATOR GEN_USERCREDENTIALS_ID TO 13;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE DAYSAMPLES (
    SAMPLETIME          TIMESTAMP NOT NULL,
    POWERAKKU           FLOAT,
    POWERGRID           FLOAT,
    POWERLOAD           FLOAT,
    POWERPV             FLOAT,
    RELAUTONOMY         FLOAT,
    RELSELFCONSUMPTION  FLOAT
);

CREATE TABLE DAYSTATS (
    SAMPLETIME     DATE NOT NULL,
    ENPRODUCED     FLOAT,
    ENCONSUME      FLOAT,
    ENGRID         FLOAT,
    ENTOGRID       FLOAT,
    BEGINPRODUCED  FLOAT,
    BEGINCONSUME   FLOAT,
    BEGINGRID      FLOAT,
    BEGINTOGRID    FLOAT,
    LASTUPDATE     TIMESTAMP
);

CREATE TABLE ENERGYACCUM (
    FROMTIME    TIMESTAMP NOT NULL,
    TOTIME      TIMESTAMP NOT NULL,
    ENFROMGRID  FLOAT,
    ENTOGRID    FLOAT,
    ENLOAD      FLOAT,
    ENPV        FLOAT,
    ENPVUSE     FLOAT
);

CREATE TABLE FIDOCHALLENGES (
    CHALLENGE  VARCHAR(256),
    DATA       VARCHAR(4096),
    MODIFIED   TIMESTAMP
);

CREATE TABLE FRONIUSSESSIONS (
    SESSIONID  VARCHAR(64) NOT NULL,
    IPADDRESS  VARCHAR(128),
    EXPIRES    TIMESTAMP,
    UID        INTEGER
);

CREATE TABLE FRONIUSUSERS (
    UID    INTEGER NOT NULL,
    UNAME  VARCHAR(128) NOT NULL
);

CREATE TABLE METERVALUES (
    METER_TIMESTAMP    TIMESTAMP NOT NULL,
    EN_MINUS_ABSOLUTE  FLOAT,
    EN_PLUS_ABSOLUTE   FLOAT,
    EN_SUM_CONSUMED    FLOAT,
    EN_SUM_PRODUCED    FLOAT,
    POWER_APP_P1       FLOAT,
    POWER_APP_P2       FLOAT,
    POWER_APP_P3       FLOAT,
    POWER_APP_SUM      FLOAT,
    INVERTERPTOTALROD  FLOAT,
    INVERTERPAC        FLOAT,
    INVERTERYEARPROD   FLOAT,
    INVERTERDAYENPROD  FLOAT
);

CREATE TABLE SAMPLES (
    SAMPLETIME          TIMESTAMP NOT NULL,
    POWERPV             FLOAT,
    POWERLOAD           FLOAT,
    POWERGRID           FLOAT,
    RELAUTONOMY         FLOAT,
    RELSELFCONSUMPTION  FLOAT
);

CREATE TABLE SYSVALUES (
    VALNAME     VARCHAR(32),
    LASTUPDATE  TIMESTAMP,
    VALDATA     VARCHAR(128)
);

CREATE TABLE USERCREDENTIALS (
    ID           INTEGER NOT NULL,
    UID          INTEGER,
    LOGINTYPE    INTEGER,
    CREDENTIALS  VARCHAR(128),
    ENABLED      INTEGER,
    DATA         VARCHAR(4096),
    MODIFIED     TIMESTAMP,
    SIGCOUNTER   INTEGER,
    FMT          VARCHAR(16),
    USERHANDLE   VARCHAR(128)
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE DAYSAMPLES ADD CONSTRAINT PK_DAYSAMPLES PRIMARY KEY (SAMPLETIME);
ALTER TABLE DAYSTATS ADD PRIMARY KEY (SAMPLETIME);
ALTER TABLE ENERGYACCUM ADD PRIMARY KEY (FROMTIME);
ALTER TABLE FRONIUSUSERS ADD PRIMARY KEY (UID);
ALTER TABLE METERVALUES ADD CONSTRAINT PK_METERVALUES PRIMARY KEY (METER_TIMESTAMP);
ALTER TABLE SAMPLES ADD CONSTRAINT PK_SAMPLES PRIMARY KEY (SAMPLETIME);
ALTER TABLE USERCREDENTIALS ADD CONSTRAINT PK_USERCREDENTIALS PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE USERCREDENTIALS ADD CONSTRAINT FK_USERCREDENTIALS_1 FOREIGN KEY (UID) REFERENCES FRONIUSUSERS (UID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: FRONIUSUSERS_BIO */
CREATE TRIGGER FRONIUSUSERS_BIO FOR FRONIUSUSERS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  begin
   if (new.uid is null) then
   begin
     new.uid = gen_id( gen_froniususers_id, 1 );
   end
 end
end
^

/* Trigger: USERCREDENTIALS_BI0 */
CREATE TRIGGER USERCREDENTIALS_BI0 FOR USERCREDENTIALS
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  begin
   if (new.id is null) then
   begin
     new.id = gen_id( gen_usercredentials_id, 1 );
   end
 end
end
^
SET TERM ; ^
